---
title: 910ths
timezone: Asia/Riyadh
collections:
  events:
    title: 00_Events
    output: true
  news:
    title: 00_News
    output: true
  slider:
    title: 01_Slider
    output: false
  products:
    title: 02_Products
    output: false
  products-section:
    title: 02_Products_section
    output: false
  banner:
    title: 03_Banner
    output: false
  video-banner:
    title: 04_Video_banner
    output: false
  steps-section:
    title: 05_Steps_section
    output: false
  partners:
    title: 06_Partners
    output: false
  partners-section:
    title: 06_Partners_section
    output: false
  quote:
    title: 10_Quote
    output: false
  values-section:
    title: 11_Values_section
    output: false
  work-offers:
    title: 20_Work_offers
    output: true
    permalink: "/career/:path"
  work-offers-section:
    title: 20_Work_offers_section
    output: false
  work-offers-category:
    title: 20__Work_offers_category
    output: false
  work-offers-location:
    title: 20__Work_offers_location
    output: false
  work-offers-type:
    title: 20__Work_offers_type
    output: false
  management:
    title: 99_Management
    output: false
  posts:
    title: Posts
    output: true
  products-aligments:
    title: Products_aligments
    output: false
  products-layouts:
    title: Products_layouts
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: events
  values:
    layout: events-single
    start_at: ''
    end_at: ''
    location:
      lat: ''
      lng: ''
    address: ''
    info_text: ''
    arabic_title: ''
    arabic_content_md: ''
    arabic_address: ''
    arabic_info_text: ''
- scope:
    path: ''
    type: news
  values:
    layout: news-single
    excerpt: ''
    arabic_title: ''
    arabic_content_md: ''
    arabic_excerpt: ''
    images: []
- scope:
    path: ''
    type: slider
  values:
    header: ''
    arabic_header: ''
    description: ''
    arabic_description: ''
    button: ''
    arabic_button: ''
    button_url: ''
    arabic_button_url: ''
    button_uat_url: ''
    arabic_button_uat_url: ''
    bg_video_asset: ''
    bg_video_poster_asset: ''
    bg_image_asset: ''
    is_bg_image_active: false
    image_offset_x: ''
    image_offset_y: ''
- scope:
    path: ''
    type: products
  values:
    title_text: ''
    arabic_title_text: ''
    description: ''
    arabic_description: ''
    button_url: ''
    arabic_button_url: ''
    button_uat_url: ''
    arabic_button_uat_url: ''
    background_asset: ''
    products_layout: ''
    products_aligment: ''
    is_dark: false
- scope:
    path: ''
    type: products-section
  values:
    header: ''
    arabic_header: ''
    text: ''
    arabic_text: ''
    02_products:
    - 
- scope:
    path: ''
    type: banner
  values:
    header: ''
    arabic_header: ''
    text: ''
    arabic_text: ''
    description: ''
    arabic_description: ''
    button: ''
    arabic_button: ''
    button_url: ''
    arabic_button_url: ''
    button_uat_url: ''
    arabic_button_uat_url: ''
    is_button_active: true
    video_asset: ''
    is_video_active: true
    poster_asset: ''
- scope:
    path: ''
    type: video-banner
  values:
    header: ''
    arabic_header: ''
    text: ''
    arabic_text: ''
    description: ''
    arabic_description: ''
    video_image: img/video-mask.png
    background_asset: ''
    video_asset: ''
    arabic_video_asset: ''
    yt_video_id: ''
    arabic_yt_video_id: ''
    is_youtube_active: false
- scope:
    path: ''
    type: steps-section
  values:
    header: ''
    arabic_header: ''
    text: ''
    arabic_text: ''
    list:
    - title: ''
      arabic_title: ''
      description: ''
      arabic_description: ''
      image: ''
- scope:
    path: ''
    type: partners
  values:
    image: ''
    link: ''
    arabic_link: ''
    is_open_in_new_tab: false
- scope:
    path: ''
    type: partners-section
  values:
    text: ''
    arabic_text: ''
    description: ''
    arabic_description: ''
    button: ''
    arabic_button: ''
    button_url: ''
    arabic_button_url: ''
    button_uat_url: ''
    arabic_button_uat_url: ''
    06_partners:
    - 
    background_asset: ''
    background_hex: ''
- scope:
    path: ''
    type: products-layouts
  values:
    value: ''
- scope:
    path: ''
    type: products-aligments
  values:
    value: ''
    value_content: ''
- scope:
    path: ''
    type: quote
  values:
    quote: ''
    arabic_quote: ''
    avatar_image: ''
    author: ''
    arabic_author: ''
    company_position: ''
    arabic_company_position: ''
    company: ''
    arabic_company: ''
- scope:
    path: ''
    type: values-section
  values:
    header_text: ''
    arabic_header_text: ''
    list:
    - image: ''
      title: ''
      arabic_title: ''
      information: ''
      arabic_information: ''
- scope:
    path: ''
    type: work-offers
  values:
    layout: work-single
    short_desc: ''
    20__work_offers_category: ''
    20__work_offers_type: ''
    20__work_offers_location: ''
    amount:
      min: ''
      max: ''
    deadline_at: ''
    arabic_title: ''
    arabic_content_md: ''
    arabic_short_desc: ''
- scope:
    path: ''
    type: work-offers-section
  values:
    header_text: ''
    arabic_header_text: ''
    20_work_offers:
    - ''
- scope:
    path: ''
    type: work-offers-category
  values:
    value: ''
    arabic_value: ''
- scope:
    path: ''
    type: work-offers-location
  values:
    country: ''
    lat: ''
    lng: ''
    arabic_title: ''
    arabic_country: ''
- scope:
    path: ''
    type: work-offers-type
  values:
    value: ''
    arabic_value: ''
version: Hi9yPAU3TF
title_suffix: Nine Tenths
arabic_title_suffix: تسعة أعشار
esso:
  base_url: https://esso.910ths.sa
  client_id: 8
  base_uat_url: https://uat-esso.910ths.sa
  client_uat_id: 24
esso_api:
  base_url: https://esso-api.910ths.sa/api
  base_uat_url: https://uat-esso-api.910ths.sa/api
zendesk_subdomain: 910ths
hotjar_id: 511570
hotjar_snippet_version: 5
google_analytics_ua: 
google_tag_manager_gtm: GTM-PGTQKW3
google_maps_js_api: AIzaSyCy6hRFVqBgV_JH5DLWLVXqaj4hAdvjdIw
imgix:
  source: 910.imgix.net
  secure_url_token: T7N3qyEsRwdKWWnV
06_partners_section: Default
description: Our innovated solutions develop projects, Support entrepreneurs, Facilitate
  access to investors, and enables you to expand your business. We are sponsored by
  HRDF Human Resources Development Fund
arabic_description: مبادرة وطنية تقدم حلول مبتكرة لدعم ريادة الأعمال والمنشآت الناشئة
  والراغبة في التوسع
permalink: pretty
markdown: kramdown
exclude:
- gulpfile.js
- node_modules
- npm-debug.log
- package.json
- README.md
- scss
- js/global.js
- js/jquery-3.2.1.min.js
- js/isotope.pkgd.min.js
gems:
- jekyll-multiple-languages-plugin
- jekyll-sitemap
- jekyll-paginate-v2
- jekyll/imgix
languages:
- ar
- en
exclude_from_localizations:
- css
- font
- img
- js
- scss
- globals
pagination:
  enabled: true
  per_page: 10
  permalink: "/page/:num/"
excerpt_separator: 
